theme: jekyll-theme-cayman
title: Converting Word Documents into Markdown Files Using Pandoc!
description: NOTE: This guide is shown using Microsoft Windows. Verify which operating your system your laptop or computer uses before proceeding with steps.
